import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillGithub} from 'react-icons/ai';
import Image from 'next/image';
import deved from '../public/picture/astronut.png';
import desk from '../public/picture/Desk.png';
import web from '../public/picture/website.png';
import cal from '../public/picture/calulator.png';
import web1 from '../public/picture/Web1.png';
import web2 from '../public/picture/web2.png';
import {useState} from "react"; {/* for dark mode*/}



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Wesley Sum</title>
        <meta name="description" content="Generated by Wesley Sum" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developedbyed</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
                </li>
                <li><a className="bg-gradient-to-r from bg-teal-700 text-white px-4 py-2 rounded-md ml-8"href='#'>
                  Resume</a></li>
              </ul>
            </nav>
            <div className='text-center p-10'>
              <h2 className='text-5xl py-2 text-teal-700 font-medium md:test-6xl'>Wesley Sum</h2>
              <h3 className='text-2xl py-2 md:text-3xl'> Developer and designer</h3>
              <p className='tex-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto'>
                I am currently a student studying in Orange Coast College studying Computer Science. 
                I am interested in working on a Quantum computing field.
              </p>
            </div>
            <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillTwitterCircle className=' cursor-pointer'/>
            <AiFillLinkedin className=' cursor-pointer'/>
            <AiFillGithub className=' cursor-pointer'/>
            </div>
            <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-t-xl w-60 h-60 mt-20 ovoverflow-hidden md:h-96 md:w-96' >
              <Image src={deved} alt='Cartoon' layout='fill' objectFit='cover '/>
            </div>
          </section>

          {/* second page */}
          <section>
            <div>
              <h3 className='text-3xl py-1'>Skills I have</h3>
              <p className='text-md py-2 leading-8 text-gray-800'>
                Python, C++, Java....
              </p>
            </div>
            <div className='lg:flex gap-10 md:test-l max-w-l mx-auto'>
              <div className='text-center shadow-lg p-8 rounded-xl my-10'>
                <Image src={desk} alt='desksetup' height={200} width={200}/> {/* need to fix picture*/}
                <h3 className='text-lg font-medium pt-8 pb-2'>Nice desk setup</h3>
                <p className='py-2'>
                  I like to record my griding moment to moltivates other
                </p>
                <h4 className='py-4 text text-teal-700 font-bold'>Technology I use while study</h4>
                <p className='text-gray-800 py-1'>Monitor</p>
                <p className='text-gray-800 py-1'>Laptop</p>
                <p className='text-gray-800 py-1'>Ipad</p>
              </div>

              <div className='text-center shadow-lg p-8 rounded-xl my-10'>
                <Image src={web} alt='website portfolio' height={200} width={200}/> {/* need to fix picture*/}
                <h3 className='text-lg font-medium pt-8 pb-2'>Nice desk setup</h3>
                <p className='py-2'>
                  This is my own personal website
                </p>
                <h4 className='py-4 text text-teal-700 font-bold'>Tool I use</h4>
                <p className='text-gray-800 py-1'>Tailwind</p>
                <p className='text-gray-800 py-1'>javascript</p>
                <p className='text-gray-800 py-1'>css</p>
              </div>

              <div className='text-center shadow-lg p-8 rounded-xl my-10'>
                <Image src={cal} alt='calculator' height={200} width={200}/> {/* need to fix picture*/}
                <h3 className='text-lg font-medium pt-8 pb-2'>Nice desk setup</h3>
                <p className='py-2'>
                  My first personal project
                </p>
                <h4 className='py-4 text text-teal-700 font-bold'>Tool I use</h4>
                <p className='text-gray-800 py-1'>html</p>
                <p className='text-gray-800 py-1'>css</p>
                <p className='text-gray-800 py-1'>JS</p>
              </div>
            </div>
          </section>
          <section>
            <div>
              <h3 className='text-3xl py-2'>Portfolio</h3>
              <p className='tex-md py-5 leading-8 text-gray-800'>
                I am currently a student studying in <span className='text-orange-500'>Orange Coast College</span> studying Computer Science. 
                I am interested in working on a Quantum computing field.I started of my journey as a cs student
              </p>
            </div>
            <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'> 
              <div className='basis-1/3 flex-1'>
                <Image src={web1} alt='view1' className='rounded-lg object-cover' height={200} width={100} layout="responsive"/>
              </div>
              <div className='basis-1/3 flex-1'>
                <Image src= {web2} alt='view2' className='rounded-lg object-cover' height={200} width={100}layout="responsive"/>
              </div>
            </div>

          </section>


      </main>
    </div>
  )
}
